name: Cypress Tests

on: [push]

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        meteor: [ '2.8.0' ]
    
    steps:
    
      - uses: cypress-io/github-action@v4
      - uses: actions/setup-node@v3
             

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        with:
          browser: chrome
          build: meteor npm install
          start: meteor run
          wait-on: "http://localhost:3000"
          run: meteor run && npm run cypress:headless  --record --spec "cypress/e2e/TestesE2E.cy.js"
